cacheFolder: .yarn/cache

nodeLinker: node-modules
# nodeLinker: pnpm

logFilters:
  # esbuild-*@* The darwin-arm64 architecture is incompatible with this module, link skipped.
  - code: 'YN0076'
    level: discard

packageExtensions:
  '@commitlint/load@*':
    dependencies:
      '@types/node': '*'
  '@mdx-js/loader@*':
    dependencies:
      'react': '17.0.2'
  '@storybook/vue3@*':
    dependencies:
      'typescript': '*'
  # Due to storybook-vite-builder
  '@project-name/core-components@*':
    dependencies:
      '@babel/core': '*'
      '@vue/compiler-sfc': '*'
      'babel-jest': '*'
      'babel-loader': '*'
      'webpack': '*'
  'storybook-builder-vite@*':
    dependencies:
      'react': '17.0.2'
      'react-dom': '17.0.2'
  # Due to storybook-vite-builder
  'project-name@*':
    dependencies:
      '@babel/core': '*'
      '@vue/compiler-sfc': '*'
      'babel-jest': '*'
      'babel-loader': '*'
      'webpack': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
